### ISSUE TITLE
Binary search more costly than needed.

### ISSUE THREAD

**Issue by raphael-proust** [yongrenjie/wcwidth-ocaml#1]
The binary search function in the source code is

```
let binary_search (table : interval list) (i : int) : bool =
  let min, max = 0, List.length table - 1 in
  if i < (List.hd table).first || i > (List.nth table max).last
  then false
  else (
    let rec inner_search min max =
      if max < min
      then false
      else (
        let mid = (min + max) / 2 in
        if i > (List.nth table mid).last
        then inner_search (mid + 1) max
        else if i < (List.nth table mid).first
        then inner_search min (mid - 1)
        else true)
    in
    inner_search min max)
;;
```

Note that in OCaml, lists are traversed one element at a time. For example `List.length table` takes as long to evaluate as there are elements in the list `table`. Similarly, `List.nth table max` takes `max` steps to evaluate.

The repeated calls to `List.nth` are more costly than necessary. (Although the list of characters are relatively small so I guess it might not be noticeable.)

---------------------

I'd recommend using arrays instead. Replace
- `[`…`]` in `char_list.ml` with `[|`…`|]`,
- `List.length` with `Array.length`
- `List.nth` with `Array.get`
- `List.hd` with `Array.get` with `0` as index

**Comment by yongrenjie** [comment]
Thanks again @raphael-proust! :)
